version: '3.9'

services:

  # 🧭 Discovery Server (Eureka)
  discovery-server:
    build:
      context: ./discovery-server
    ports:
      - "8761:8761"
    networks:
      - learne-network
    environment:
      - spring.profiles.active=default
      - eureka.instance.hostname=discovery-server
      - eureka.client.register-with-eureka=false
      - eureka.client.fetch-registry=false
      - eureka.client.service-url.defaultZone=http://discovery-server:8761/eureka/

  # 🌐 API Gateway
  api-gateway:
    build:
      context: ./api-gateway
    depends_on:
      - discovery-server
    ports:
      - "8080:8080"
    networks:
      - learne-network
    environment:
      - spring.profiles.active=default
      - eureka.client.service-url.defaultZone=http://discovery-server:8761/eureka
      - eureka.instance.prefer-ip-address=true
      - eureka.client.register-with-eureka=true
      - eureka.client.fetch-registry=true

  # 👤 Profile Service
  profile-service:
    build:
      context: ./profile-service
    depends_on:
      - discovery-server
      - mysql-profile
      - kafka
      - notification-service
    networks:
      - learne-network
    environment:
      - spring.profiles.active=default
      - spring.datasource.url=jdbc:mysql://mysql-profile:3306/profile-service
      - spring.datasource.username=root
      - spring.datasource.password=password
      - spring.kafka.bootstrap-servers=kafka:9092
      - eureka.client.service-url.defaultZone=http://discovery-server:8761/eureka
      - eureka.instance.prefer-ip-address=true
      - eureka.client.register-with-eureka=true
      - eureka.client.fetch-registry=true

  # 📘 Learne Service
  learne-service:
    build:
      context: ./learne-service
    depends_on:
      - discovery-server
      - mysql-learne
    networks:
      - learne-network
    environment:
      - spring.profiles.active=default
      - spring.datasource.url=jdbc:mysql://mysql-learne:3306/learne-service
      - spring.datasource.username=root
      - spring.datasource.password=password
      - eureka.client.service-url.defaultZone=http://discovery-server:8761/eureka
      - eureka.instance.prefer-ip-address=true
      - eureka.client.register-with-eureka=true
      - eureka.client.fetch-registry=true

  # ✉️ Notification Service
  notification-service:
    build:
      context: ./notification-service
    depends_on:
      - discovery-server
      - kafka
    networks:
      - learne-network
    environment:
      - spring.profiles.active=default
      - SENDGRID_API_KEY=${SENDGRID_API_KEY}
      - FROM_EMAIL=${FROM_EMAIL}
      - spring.kafka.bootstrap-servers=kafka:9092
      - eureka.client.service-url.defaultZone=http://discovery-server:8761/eureka
      - eureka.instance.prefer-ip-address=true
      - eureka.client.register-with-eureka=true
      - eureka.client.fetch-registry=true

  # 🐬 MySQL para Profile
  mysql-profile:
    image: mysql:8
    restart: always
    ports:
      - "3307:3306"
    environment:
      MYSQL_DATABASE: profile-service
      MYSQL_ROOT_PASSWORD: password
    networks:
      - learne-network

  # 🐬 MySQL para Learne
  mysql-learne:
    image: mysql:8
    restart: always
    ports:
      - "3308:3306"
    environment:
      MYSQL_DATABASE: learne-service
      MYSQL_ROOT_PASSWORD: password
    networks:
      - learne-network

  # 🦍 Kafka + Zookeeper
  zookeeper:
    image: confluentinc/cp-zookeeper:7.3.2
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
    networks:
      - learne-network

  kafka:
    image: confluentinc/cp-kafka:7.3.2
    depends_on:
      - zookeeper
    ports:
      - "9092:9092"
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
    networks:
      - learne-network

networks:
  learne-network:
    driver: bridge
